version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    docker:
      - image circleci/jdk8:0.1.1
    jobs:
      - maven/test # checkout, build, test, and upload test results

